server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path(route='about', view=views.about, name='about'),

    # path for contact us view
    path(route='contact', view=views.contact, name='contact'),
    # path for registration
    path(route='registration', view=views.registration_request, name='registration'),
    # path for login
    path(route='login',view=views.login_request,name='login'),

    # path for logout
    path(route='logout',view=views.logout_request,name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view
    path(route='dealer/<int:dealer_id>/',view=views.get_dealer_details,name='dealer_details'),

    # path for add a review view
    path(route='add_review/<int:dealer_id>/',view=views.add_review,name='add_review')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

# <HINT> Create a Car Make model 
class CarMake(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=300)

    def __str__(self):
        return self.name


# <HINT> Create a Car Model model `class CarModel(models.Model):`:
class CarModel(models.Model):
    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    type_ch = models.CharField(max_length=10, choices=(('BMW', 'BMW',), ('Benz', 'Benz'), ('Swift', 'Swift')))
    id = models.IntegerField(null=False,primary_key=True)
    year = models.DateField()

    def __str__(self):
        return self.name


# <HINT> Create a plain Python class `CarDealer` to hold dealer data
class CarDealer:
    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        self.address = address
        self.city = city
        self.full_name = full_name
        self.id = id
        self.lat = lat
        self.long = long
        self.short_name = short_name
        self.st = st
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name

# <HINT> Create a plain Python class `DealerReview` to hold review data
class DealerReview:
    def __init__(self, dealership, name, purchase, review):
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        self.purchase_date = ""
        self.car_make = ""
        self.car_model = ""
        self.car_year = ""
        self.sentiment = ""
        self.id = ""

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import *
from .restapis import *
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
def about(request):
 return render(request,'djangoapp/about.html')


# Create a `contact` view to return a static contact page
def contact(request):
    return render(request,'djangoapp/contact.html')

# Create a `login_request` view to handle sign in request
def login_request(request):
    if request.method=="POST":
        print(request.POST['username'])
        print(request.POST['password'])
        user=authenticate(username=request.POST['username'],password=request.POST['password'])
        print(user)
        if user is not None:
            login(request, user)
            
            return redirect('djangoapp:index')
        
        return render(request,'djangoapp/index.html', {'error':'wrong pwd or username'})

    return render(request,'djangoapp/index.html')


# Create a `logout_request` view to handle sign out request
def logout_request(request):
    if request.method =='GET':
        #print(request.POST.user)
        logout(request)
        #print(user.username)
    return redirect('djangoapp:index')

# Create a `registration_request` view to handle sign up request
def registration_request(request):
    if request.method=='POST':
        #print(request.POST['password'],request.POST['password2'])
        if request.POST['password']==request.POST['password2']:
            try:
                User.objects.get(username=request.POST['username'])
                return render(request,'djangoapp/registration.html',{'error':'Username is taken!'})
            except User.DoesNotExist:
                user=User.objects.create_user(username=request.POST['username'],password=request.POST['password'])
                login(request,user)
                return redirect('djangoapp:index')
        else:
            return render(request,'djangoapp/registration.html',{'error':'Password doesnt match'})
    return render(request, 'djangoapp/registration.html')


# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "https://eu-de.functions.appdomain.cloud/api/v1/web/mishrajgc_myspace1/dealership-package/get-dealership"
        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)
        # Concat all dealer's short name
        #dealer_names = ' '.join([dealer.short_name for dealer in dealerships])
        # Return a list of dealer short name
        context["dealerships"] = dealerships
        #return HttpResponse(dealer_names)
        return render(request, 'djangoapp/index.html', context)

# Create a `get_dealer_details` view to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    if request.method == "GET":
        context = {}
        url = "https://eu-de.functions.appdomain.cloud/api/v1/web/mishrajgc_myspace1/dealership-package/review"
        reviews = get_dealer_reviews_from_cf(url,dealer_id)
        
        print(reviews)
        context["reviews"] = reviews
        dealer = get_dealer_from_cf_by_id(
            "https://eu-de.functions.appdomain.cloud/api/v1/web/mishrajgc_myspace1/dealership-package/get-dealership", dealer_id)
        print(dealer)
        context["dealer"] = dealer
        
            
        return render(request, 'djangoapp/dealer_details.html', context)


def add_review(request, dealer_id):
    context = {}
    if request.method == "GET":
        url = "https://eu-de.functions.appdomain.cloud/api/v1/web/mishrajgc_myspace1/dealership-package/get-dealership"
        dealer = get_dealer_from_cf_by_id(url, dealer_id)
        cars = CarModel.objects.filter(dealer_id=dealer_id)
        context["cars"] = cars
        context["dealer"] = dealer
        return render(request, 'djangoapp/add_review.html', context)

    if request.method == "POST":
        url = "https://eu-de.functions.appdomain.cloud/api/v1/web/mishrajgc_myspace1/dealership-package/post_review/"      
        if 'purchasecheck' in request.POST:
            was_purchased = True
        else:
            was_purchased = False

        cars = CarModel.objects.filter(dealer_id=dealer_id)
        print(cars,"CARS")
        for car in cars:
            print(car,"car")
            if car.id == int(request.POST['car']):
                review_car = car  
        review = {}
        review["time"] = datetime.utcnow().isoformat()
        review["name"] = request.POST['name']
        review["dealership"] = dealer_id
        review["id"]=dealer_id
        review["review"] = request.POST['content']
        review["purchase"] = was_purchased
        review["purchase_date"] = request.POST['purchasedate']
        review["car_make"] = review_car.car_make.name
        review["car_model"] = review_car.name
        review["car_year"] = review_car.year.strftime("%Y")
        json_payload = {}
        json_payload["review"] = review
        response = post_request(url, json_payload,dealer_id=dealer_id)
        return redirect("djangoapp:dealer_details", dealer_id=dealer_id)

server/djangoapp/templates/basetag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>
<body>
    <!--Add a nav bar here -->
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}
</body>
</html>

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review - About</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link
      href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"
      rel="stylesheet"
    />
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'djangoapp:index' %}"
        >Dealership Review</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:index' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'djangoapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="ml-auto">
          <span class="mr-2">{{ user.first_name }}({{ user.username }})</span>
          <a href="{% url 'djangoapp:logout' %}">Log out</a>
        </div>
        {% else %}
        <form
          class="form-inline ml-auto"
          action="{% url 'djangoapp:login' %}"
          method="post"
        >
          {% csrf_token %}
          <input
            class="form-control mr-sm-2"
            type="text"
            placeholder="Username"
            name="username"
            required
          />
          <input
            class="form-control mr-sm-2"
            type="password"
            placeholder="Password"
            name="psw"
            required
          />
          <button class="btn btn-primary my-2 my-sm-0 mr-2" type="submit">
            Login
          </button>
          <a
            class="btn btn-outline-primary my-2 my-sm-0"
            href="{% url 'djangoapp:registration' %}"
            >Sign Up</a
          >
        </form>
        {% endif %}
      </div>
    </nav>
    <div class="jumbotron">
      <h1 class="text-center mb-5">
        Welcome to Best Cars dealership, home to the best cars in North America.
        <br />
        We sell domestic and imported cars at reasonable prices.
      </h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim id est laborum.
      </p>
    </div>
    <div style="min-height: 500px" class="text-center">
      
    </div>
    <footer class="bg-light text-center text-lg-start mt-5">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022
        <a class="text-dark" href="{% url 'djangoapp:index' %}"
          >Dealership Review</a
        >
      </div>
    </footer>
  </body>
</html>

server/djangoapp/templates/djangoapp/add_review.html
{% extends 'djangoapp/index.html' %}
    
    {% block content %}
    <!--Add review form here -->
    <div style="min-height: 190px"></div>
          <div class="container">
            <div class="row">
                <div class="col-md">
                    <h4 class="mb-5"> Add a review for <strong>{{dealer.full_name}}</strong></h4>
                    <form action = "{% url 'djangoapp:add_review' dealer.id %}" method="post">
                        <H5>Your Name:</H5><br>
                        {% csrf_token %}
                        <input class="form-control" id="name" name="name" size="30" required></textarea><br>
                        <H5>Enter the review content:</H5><br>
                        <textarea class="form-control" id="content" name="content" rows="2" required></textarea><br>
                        <div class = "form-check mt-5">
                            <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
                            <label class="form-check-label">Has purchased car from {{dealer.full_name}} ?<label> <span style="color: gray; font-weight: 300; padding-left: 5px;">(select purchased car information below if checked)</span>
                        </div>
                        <div class="d-flex mt-3">
                            <div class="mr-5">
                                <h5>Select your car (model-make-year):</h5><br/>
                                <select name="car" id="car" class="form-select form-select-sm mt-0" aria-label=".form-select-sm example"><br>
                                    {% for car in cars %}       
                                        <option selected value={{car.id}}>{{car.car_make.name}}-{{car.name}}-{{ car.year|date:"Y" }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div>
                                <h5>Select Your Purchase Date:</h5><br/>
                                <div class = "input-group date" data-provide="datepicker-inline"> 
                                    <input class="date-own form-control" type="date" name="purchasedate" id="purchasedate"><br>
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary mt-5" type="submit">Add review</button>
                    </form>
                </div>
            </div>
          </div>
          <div style="min-height: 200px"></div>
          {% endblock %}
    

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review - Contact</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link
      href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"
      rel="stylesheet"
    />
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
  </head>

  <body class="vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'djangoapp:index' %}"
        >Dealership Review</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:index' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:about' %}">About</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="ml-auto">
          <span class="mr-2">{{ user.first_name }}({{ user.username }})</span>
          <a href="{% url 'djangoapp:logout' %}">Log out</a>
        </div>
        {% else %}
        <form
          class="form-inline ml-auto"
          action="{% url 'djangoapp:login' %}"
          method="post"
        >
          {% csrf_token %}
          <input
            class="form-control mr-sm-2"
            type="text"
            placeholder="Username"
            name="username"
            required
          />
          <input
            class="form-control mr-sm-2"
            type="password"
            placeholder="Password"
            name="psw"
            required
          />
          <button class="btn btn-primary my-2 my-sm-0 mr-2" type="submit">
            Login
          </button>
          <a
            class="btn btn-outline-primary my-2 my-sm-0"
            href="{% url 'djangoapp:registration' %}"
            >Sign Up</a
          >
        </form>
        {% endif %}
      </div>
    </nav>
    <div class="container mt-5">
      <div class="col-md-4">
        <address>
          <strong>Dealership Review Inc.</strong><br />
          1234 Example Street<br />
          Antartica, Example 0987<br />
          <a href="mailto:#">exam.ple@example.com</a>
        </address>
      </div>
    </div>
    <div style="min-height: 725px"></div>
    <footer class="bg-light text-center text-lg-start mt-5">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022
        <a class="text-dark" href="{% url 'djangoapp:index' %}"
          >Dealership Review</a
        >
      </div>
    </footer>
  </body>
</html>

server/djangoapp/templates/djangoapp/dealer_details.html
{% extends 'djangoapp/index.html' %}
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head> -->


    
    {% block content%}
    <div class="container mt-5">
        <div class="rows">
          <div class="col-md mb-5">
            <h3>Reviews for <strong>{{ dealer.full_name }}</strong></h3>
          </div>
          <div class="col-md">
            {% if reviews %}
            <div class="card-columns">
            {% for review in reviews %}
              {% if review.id == dealer.id %}
                 
              <div class="card">
                {% if review.sentiment == 'positive' %}
                <img
                  class="card-img-left"
                  src="{{MEDIA_URL}}/emoji/positive.png"
                  style="width: 30px; height: 30px"
                />
                {% endif %} {% if review.sentiment == 'neutral' %}
                <img
                  class="card-img-left"
                  src="{{MEDIA_URL}}/emoji/neutral.png"
                  style="width: 30px; height: 30px"
                />
                {% endif %} {% if review.sentiment == 'negative' %}
                <img
                  class="card-img-left"
                  src="{{MEDIA_URL}}/emoji/negative.png"
                  style="width: 30px; height: 30px"
                />
                {% endif %}
                {% if review.name %}
                <label class="card-title">{{review.name}} </label>
                {% endif %}
                <div class="card-body bg-light">
                    
                  {% if review.purchase %}
                  <h5 class="card-title">{{review.car_make}}, {{review.car_model}}</h5>
                  <h5 class="card-title">{{review.car_year}}</h5>
                  {% else %} 
                  <h5 class="card-title">Reviewer did not buy any car.</h5>
                  <h5 class="card-title" style="color: #f8f9fa;">.</h5>
                  {% endif %}
                  </h5>
                  <label class="card-title">{{review.review}} </label>
                </div>
              </div>
              {% endif %}
            {% endfor %}
            {% else %}
            <div class="card-columns">
              <div class="card">
                <div class="card-body bg-light">
                  <h5 class="card-title">No reviews yet</h5>
                  <a class="btn btn-link" method= "GET" href="{% url 'djangoapp:add_review' dealer.id %}">Be first to add a review?</a>
                </div>
              </div>
            </div>
            {% endif %}
           
            </div>
            <br>
            <div>
                <a class="text-success" href="{% url 'djangoapp:index' %}"
                ><strong>Dealership Review</strong></a></div>
               <br>
               <div> <a class="text-success" href="{% url 'djangoapp:add_review' dealer.id %}"><strong>Add another review</strong></a>
              </div>
          </div>
        </div>
        {% if reviews %}
        <div style="min-height: 560px"></div>
        {% else %}
        <div style="min-height: 625px"></div>
        {% endif %} 
      </div>
      
        
      </div>
    <!-- Add reviews as cards -->
    {%endblock content%}
    </body>

</html>

server/djangoapp/templates/djangoapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <title>"Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" type='text/css' href="{% static '/admin/css/base.css' %}">
</head>

    
    <body>
    <!-- Remove this line the first time you edit this file -->
     
    <!--Add a nav bar here -->
    
    <nav style='display:flex; justify-content:space-between; background:lightgrey; align-items:center' ><a href="{% url 'djangoapp:index' %}"> Dealership Review</a>
        <a href='{% url "djangoapp:contact" %}'>Contact Us</a>
        <a href='{% url "djangoapp:about" %}'>About Us</a>
        {% if not user.is_authenticated %}
        <form method='POST' action="{% url 'djangoapp:login' %}" style='display:flex; justify-content:space-between'>
            {% csrf_token %}
            <input type='text' name="username" placeholder='Name'/>
            <input type='password' name="password" placeholder='Password'/>
            <input type='submit'  value='Login'>
            
        </form>
        <input type='submit'  value='Signup' style='border:none; color:darkblue' onclick="location.href='{% url 'djangoapp:registration' %}'">
        {% else %}
            <a href=#>({{user.username}})</a>
            <input type='submit' value='signout' onclick="location.href='{% url 'djangoapp:logout' %}'">
        {% endif %}
        
    </nav>
    
    {% block content %}
    

    <!--Add a dealer table here -->
    <main role="main" class="container pt-3">
        <h1 class="mt-2 mb-4">Dealerships</h1>
        <table class="table" id="table" data-filter-control="true">
            <thead>
                <tr>
                    <th data-field="id">ID</th>
                    <th data-field="full_name">Dealership Name</th>
                    <th data-field="city">City</th>
                    <th data-field="address">Address</th>
                    <th data-field="zip">ZIP Code</th>
                    <th data-field="state" data-filter-control="select">State</th>
                    
                </tr>
            </thead>
            <tbody>
                <div>
                {% if error %}
                   {{error}}
                {% endif %}
                {% if msg %}
                  {{msg}}
                {% endif %}
                </div>
                {% for dealer in dealerships %}
                
                    <tr>
                        <td>{{dealer.id}}</td>
                        <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                        <td>{{dealer.city}}</td>
                        <td>{{dealer.address}}</td>
                        <td>{{dealer.zip}}</td>
                        <td>{{dealer.st}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
    {% endblock content %}
    <footer style='height:50px; bottom:0; position:fixed; width:100%; padding:10px 0px 20px 10px; background:lightgrey'>
        <a href='{% url "djangoapp:contact" %}'>Contact Us</a>
        <a href='{% url "djangoapp:about" %}'>About Us</a>

    </footer>
    </body>
    <script>
        $(function() {
          $('#table').bootstrapTable()
        })
      </script>

</html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
    <!--Add a   registration form here -->
        <form action="{% url 'djangoapp:registration' %}" method="post">
            <div class="container"> <!--Style root div with .container class -->
                {% csrf_token %}
                <h1>Sign Up</h1>
                <hr>
                <div class="form-group"> <!--Style second div with .form-group class -->
                    <label for="username"><b>User Name</b></label>
                    <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
                    <label for="firstname"><b>First Name</b></label>
                    <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
                    <label for="lastname"><b>Last Name</b></label>
                    <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
                    <label for="psw"><b>Password</b></label>
                    <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
                    {% if message %}
                    <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                        {{ message }}
                    </div>
                    {% endif %}
                    <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
                </div>
            </div>
        </form>
    </body>
</html>

server/djangoapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Best Cars</a>
        <div class="navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:about' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </li>
            </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn btn-link" href="#">{{ user.first_name }}</a>
                <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Username" name="username" >
                    <input type="password" class="form-control" placeholder="Password" name="psw" >
                    <button class="btn btn-primary" type="submit">Login</button>
                    <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                </div>
                </form>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>